"""
Módulo de Configuración de Plantillas y Dominios CONAF
Define las estructuras requeridas para cada capa Shapefile según el protocolo de la Corporación Nacional Forestal (CONAF).
"""

from typing import Dict, List, Any, Optional

# Definición de tipos esperados mapeados a tipos nativos de GeoPandas/Pandas
# character -> 'character' (string)
# numeric -> 'numeric' (float)
# integer -> 'integer' (int)

PLANTILLAS: Dict[str, List[Dict[str, Any]]] = {
    "Area": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "N_Area", "tipo": "character", "longitud": 5, "decimales": None},
        {"nombre": "Tipo_Bos", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Limite_Predial": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Rol", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Comuna", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Suelos": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Cat_Erosio", "tipo": "character", "longitud": 2, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Rangos_pend": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Ran_Pend", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Infra_aislada": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Infra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Parcela": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "N_Rodal", "tipo": "character", "longitud": 5, "decimales": None},
        {"nombre": "N_Parc", "tipo": "character", "longitud": 5, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Referencia": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Pto", "tipo": "character", "longitud": 100, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Caminos": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Tipo_Cam", "tipo": "character", "longitud": 2, "decimales": None},
        {"nombre": "Long_Cam", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Curvas_niv": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Cot_Curva", "tipo": "integer", "longitud": 9, "decimales": None},
        {"nombre": "Long_Curva", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Hidrografia": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Tip_Dren", "tipo": "character", "longitud": 2, "decimales": None},
        {"nombre": "Tipo_Perma", "tipo": "character", "longitud": 2, "decimales": None},
        {"nombre": "Long_Dren", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Rodales": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "N_Rodal", "tipo": "character", "longitud": 5, "decimales": None},
        {"nombre": "Tipo_Bos", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Tipo_For", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Predios_vecinos": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Rol", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Comuna", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "LTE_HVDC": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Obra", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Tipo", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Tramo", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Long_LTE", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Sendero_peatonal": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Send", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Long_Send", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Area_Proyecto": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 80, "decimales": None},
        {"nombre": "Tipo", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Area_proteccion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Tipo", "tipo": "character", "longitud": 100, "decimales": None},
        {"nombre": "Nombre", "tipo": "character", "longitud": 100, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Limite_Comunal": [
        {"nombre": "Region", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Provincia", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Comuna", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Servidumbre": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Rol", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Areas_receptoras_ruido": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Receptor", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Perturbacion_ruido": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Receptor", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Perturbacion_baja_mov": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Perturbaci", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Receptoras_baja_mov": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Perturbaci", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Perturbacion_curureras": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Receptoras_curureras": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Ambiente", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Perchas": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Señaletica_velocidad": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Tipo_inst", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Rehabilitacion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Surcos": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Rehabilitacion_pendiente_30": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Recoleccion_semillas": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Sectores_recoleccion_semillas": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 10, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Areas_relocalizacion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Areas_rescate": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Especie", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Reposicion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Medida", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Revegetacion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Sitio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Region", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Provincia", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Comuna", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Area_FX_singular": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Enriquecimiento": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Sitio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Region", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Provincia", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Comuna", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Areas_ECC": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_obra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Obra_detal", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Especie", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Sup_ha", "tipo": "numeric", "longitud": 11, "decimales": 2},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Infra_incendio": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Infra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
    "Obras_conservacion": [
        {"nombre": "Nom_Predio", "tipo": "character", "longitud": None, "decimales": None},
        {"nombre": "Nom_Infra", "tipo": "character", "longitud": 50, "decimales": None},
        {"nombre": "Coord_X", "tipo": "integer", "longitud": 6, "decimales": 0},
        {"nombre": "Coord_Y", "tipo": "integer", "longitud": 7, "decimales": 0},
        {"nombre": "Fuente", "tipo": "character", "longitud": None, "decimales": None},
    ],
}

DOMINIOS_CONAF: Dict[str, List[Any]] = {
    "Tipo_Bos": ["No aplica"],
    "Tipo_For": ["No aplica"],
    "Tipo_Cam": ["1", "2", "3", "4", 1, 2, 3, 4],
    "Tip_Dren": ["1", "2", "3", "4", "5", 1, 2, 3, 4, 5],
    "Tipo_Perma": ["1", "2", 1, 2],
    "Cat_Erosio": ["1", "2", "3", "4", 1, 2, 3, 4],
    "Ran_Pend": ["0% - 10%", "10% - 30%", "30% - 45%", "45% - 60%", "60% y mas"],
}
